export const sortedByStrength = [
  { username: "NebulaDrifter", strength: 7 },
  { username: "DarkOracle", strength: 7 },
  { username: "MysticEcho", strength: 8 },
  { username: "QuantumMage", strength: 9 },
  { username: "RuneMaster", strength: 9 },
  { username: "SpiritDancer", strength: 9 },
  { username: "StarGazer", strength: 9 },
  { username: "RogueStellar", strength: 10 },
  { username: "AstralWalker", strength: 10 },
  { username: "VenomStrike", strength: 10 },
  { username: "EchoScream", strength: 10 },
  { username: "IceQueen", strength: 10 },
  { username: "MysticEye", strength: 10 },
  { username: "ShadowHunter", strength: 11 },
  { username: "VoidRunner", strength: 11 },
  { username: "AcidRain", strength: 11 },
  { username: "LunarTide", strength: 11 },
  { username: "TerraByte", strength: 11 },
  { username: "VenomFang", strength: 11 },
  { username: "SilentViper", strength: 12 },
  { username: "GravityPull", strength: 12 },
  { username: "NeonPulse", strength: 12 },
  { username: "ShadowStep", strength: 12 },
  { username: "ChronoShift", strength: 12 },
  { username: "CyberKnight", strength: 13 },
  { username: "ZenithSpark", strength: 13 },
  { username: "SolarFlare", strength: 13 },
  { username: "ChaosTheory", strength: 13 },
  { username: "PixelKnight", strength: 13 },
  { username: "SwiftArrow", strength: 13 },
  { username: "BladeRunner", strength: 13 },
  { username: "NovaBlaze", strength: 14 },
  { username: "PhantomBlade", strength: 14 },
  { username: "ApexGamer", strength: 14 },
  { username: "CrimsonTide", strength: 15 },
  { username: "BlazeRunner", strength: 15 },
  { username: "OmegaPoint", strength: 15 },
  { username: "ThunderBolt", strength: 16 },
  { username: "WildFire", strength: 16 },
  { username: "ApexHunter", strength: 16 },
  { username: "ApexPredator", strength: 17 },
  { username: "StormBringer", strength: 17 },
  { username: "SteelHeart", strength: 18 },
  { username: "FireStorm", strength: 18 },
  { username: "TitanGrip", strength: 19 },
  { username: "IronWill", strength: 19 },
  { username: "IronForge", strength: 20 },
  { username: "DragonSlayer", strength: 20 },
  { username: "TitanFall", strength: 20 },
];

export const sortedByLevelDesc = [
  { username: "ApexPredator", level: 17 },
  { username: "ApexGamer", level: 17 },
  { username: "DragonSlayer", level: 17 },
  { username: "ChronoShift", level: 17 },
  { username: "IronForge", level: 16 },
  { username: "QuantumMage", level: 16 },
  { username: "AstralWalker", level: 16 },
  { username: "SteelHeart", level: 16 },
  { username: "SpiritDancer", level: 16 },
  { username: "IronWill", level: 16 },
  { username: "FireStorm", level: 16 },
  { username: "ApexHunter", level: 16 },
  { username: "MysticEcho", level: 15 },
  { username: "TitanGrip", level: 15 },
  { username: "ThunderBolt", level: 15 },
  { username: "NebulaDrifter", level: 15 },
  { username: "RuneMaster", level: 15 },
  { username: "StormBringer", level: 15 },
  { username: "DarkOracle", level: 15 },
  { username: "OmegaPoint", level: 15 },
  { username: "StarGazer", level: 15 },
  { username: "TitanFall", level: 15 },
  { username: "NovaBlaze", level: 14 },
  { username: "ZenithSpark", level: 14 },
  { username: "BlazeRunner", level: 14 },
  { username: "ChaosTheory", level: 14 },
  { username: "LunarTide", level: 14 },
  { username: "WildFire", level: 14 },
  { username: "TerraByte", level: 14 },
  { username: "MysticEye", level: 14 },
  { username: "CrimsonTide", level: 13 },
  { username: "SolarFlare", level: 13 },
  { username: "PhantomBlade", level: 13 },
  { username: "GravityPull", level: 13 },
  { username: "SwiftArrow", level: 13 },
  { username: "IceQueen", level: 13 },
  { username: "CyberKnight", level: 12 },
  { username: "RogueStellar", level: 12 },
  { username: "VoidRunner", level: 12 },
  { username: "PixelKnight", level: 12 },
  { username: "NeonPulse", level: 12 },
  { username: "BladeRunner", level: 12 },
  { username: "ShadowStep", level: 12 },
  { username: "SilentViper", level: 11 },
  { username: "VenomStrike", level: 11 },
  { username: "AcidRain", level: 11 },
  { username: "EchoScream", level: 11 },
  { username: "ShadowHunter", level: 10 },
  { username: "FrostBite", level: 10 },
  { username: "VenomFang", level: 10 },
];

export const sortedByStaminaDesc = [
  { username: "IronForge", stamina: 20 },
  { username: "SteelHeart", stamina: 20 },
  { username: "IronWill", stamina: 20 },
  { username: "TitanFall", stamina: 20 },
  { username: "NovaBlaze", stamina: 19 },
  { username: "ThunderBolt", stamina: 19 },
  { username: "DragonSlayer", stamina: 19 },
  { username: "FireStorm", stamina: 19 },
  { username: "TitanGrip", stamina: 18 },
  { username: "BlazeRunner", stamina: 18 },
  { username: "WildFire", stamina: 18 },
  { username: "ApexPredator", stamina: 17 },
  { username: "SolarFlare", stamina: 17 },
  { username: "StormBringer", stamina: 17 },
  { username: "OmegaPoint", stamina: 17 },
  { username: "CrimsonTide", stamina: 16 },
  { username: "ApexGamer", stamina: 16 },
  { username: "SwiftArrow", stamina: 16 },
  { username: "ApexHunter", stamina: 16 },
  { username: "RogueStellar", stamina: 15 },
  { username: "PhantomBlade", stamina: 15 },
  { username: "PixelKnight", stamina: 15 },
  { username: "ShadowHunter", stamina: 14 },
  { username: "FrostBite", stamina: 14 },
  { username: "ChaosTheory", stamina: 14 },
  { username: "TerraByte", stamina: 14 },
  { username: "ZenithSpark", stamina: 13 },
  { username: "AcidRain", stamina: 13 },
  { username: "NeonPulse", stamina: 13 },
  { username: "VenomFang", stamina: 13 },
  { username: "SilentViper", stamina: 12 },
  { username: "VenomStrike", stamina: 12 },
  { username: "LunarTide", stamina: 12 },
  { username: "ShadowStep", stamina: 12 },
  { username: "VoidRunner", stamina: 11 },
  { username: "GravityPull", stamina: 11 },
  { username: "IceQueen", stamina: 11 },
  { username: "ChronoShift", stamina: 11 },
  { username: "CyberKnight", stamina: 10 },
  { username: "EchoScream", stamina: 10 },
  { username: "MysticEye", stamina: 10 },
  { username: "AstralWalker", stamina: 9 },
  { username: "RuneMaster", stamina: 9 },
  { username: "StarGazer", stamina: 9 },
  { username: "QuantumMage", stamina: 8 },
  { username: "SpiritDancer", stamina: 8 },
  { username: "NebulaDrifter", stamina: 7 },
  { username: "MysticEcho", stamina: 6 },
  { username: "DarkOracle", stamina: 6 },
];

export const sortedByEnduranceDesc = [
  { username: "IronForge", endurance: 20 },
  { username: "DragonSlayer", endurance: 20 },
  { username: "TitanGrip", endurance: 19 },
  { username: "SteelHeart", endurance: 19 },
  { username: "TitanFall", endurance: 19 },
  { username: "ThunderBolt", endurance: 18 },
  { username: "WildFire", endurance: 18 },
  { username: "ApexHunter", endurance: 18 },
  { username: "ApexPredator", endurance: 18 },
  { username: "StormBringer", endurance: 18 },
  { username: "IronWill", endurance: 18 },
  { username: "FireStorm", endurance: 18 },
  { username: "ShadowHunter", endurance: 16 },
  { username: "FrostBite", endurance: 16 },
  { username: "BlazeRunner", endurance: 16 },
  { username: "OmegaPoint", endurance: 16 },
  { username: "CrimsonTide", endurance: 15 },
  { username: "ApexGamer", endurance: 15 },
  { username: "SwiftArrow", endurance: 15 },
  { username: "RogueStellar", endurance: 14 },
  { username: "SolarFlare", endurance: 14 },
  { username: "AcidRain", endurance: 14 },
  { username: "NeonPulse", endurance: 14 },
  { username: "BladeRunner", endurance: 14 },
  { username: "SilentViper", endurance: 13 },
  { username: "VenomStrike", endurance: 13 },
  { username: "LunarTide", endurance: 13 },
  { username: "TerraByte", endurance: 13 },
  { username: "ZenithSpark", endurance: 12 },
  { username: "GravityPull", endurance: 12 },
  { username: "PixelKnight", endurance: 12 },
  { username: "VenomFang", endurance: 12 },
  { username: "NovaBlaze", endurance: 11 },
  { username: "PhantomBlade", endurance: 11 },
  { username: "EchoScream", endurance: 11 },
  { username: "ShadowStep", endurance: 11 },
  { username: "VoidRunner", endurance: 10 },
  { username: "ChaosTheory", endurance: 10 },
  { username: "ChronoShift", endurance: 10 },
  { username: "CyberKnight", endurance: 9 },
  { username: "IceQueen", endurance: 9 },
  { username: "AstralWalker", endurance: 8 },
  { username: "RuneMaster", endurance: 8 },
  { username: "StarGazer", endurance: 8 },
  { username: "QuantumMage", endurance: 7 },
  { username: "SpiritDancer", endurance: 7 },
  { username: "MysticEye", endurance: 7 },
  { username: "NebulaDrifter", endurance: 6 },
  { username: "MysticEcho", endurance: 5 },
  { username: "DarkOracle", endurance: 5 },
];

export const sortedBySpiritDesc = [
  { username: "AstralWalker", spirit: 20 },
  { username: "SpiritDancer", spirit: 20 },
  { username: "MysticEcho", spirit: 19 },
  { username: "NebulaDrifter", spirit: 19 },
  { username: "DarkOracle", spirit: 19 },
  { username: "StarGazer", spirit: 19 },
  { username: "QuantumMage", spirit: 18 },
  { username: "LunarTide", spirit: 18 },
  { username: "MysticEye", spirit: 18 },
  { username: "VoidRunner", spirit: 17 },
  { username: "RuneMaster", spirit: 17 },
  { username: "IceQueen", spirit: 17 },
  { username: "ZenithSpark", spirit: 16 },
  { username: "ChaosTheory", spirit: 16 },
  { username: "DragonSlayer", spirit: 16 },
  { username: "ChronoShift", spirit: 16 },
  { username: "ApexPredator", spirit: 15 },
  { username: "PhantomBlade", spirit: 15 },
  { username: "StormBringer", spirit: 15 },
  { username: "ShadowStep", spirit: 15 },
  { username: "CyberKnight", spirit: 14 },
  { username: "ThunderBolt", spirit: 14 },
  { username: "GravityPull", spirit: 14 },
  { username: "IronWill", spirit: 14 },
  { username: "ApexHunter", spirit: 14 },
  { username: "TitanGrip", spirit: 13 },
  { username: "ApexGamer", spirit: 13 },
  { username: "OmegaPoint", spirit: 13 },
  { username: "ShadowHunter", spirit: 12 },
  { username: "FrostBite", spirit: 12 },
  { username: "SteelHeart", spirit: 12 },
  { username: "EchoScream", spirit: 12 },
  { username: "SwiftArrow", spirit: 12 },
  { username: "BladeRunner", spirit: 12 },
  { username: "SilentViper", spirit: 11 },
  { username: "BlazeRunner", spirit: 11 },
  { username: "NeonPulse", spirit: 11 },
  { username: "FireStorm", spirit: 11 },
  { username: "CrimsonTide", spirit: 10 },
  { username: "AcidRain", spirit: 10 },
  { username: "WildFire", spirit: 10 },
  { username: "TitanFall", spirit: 10 },
  { username: "RogueStellar", spirit: 9 },
  { username: "VenomStrike", spirit: 9 },
  { username: "PixelKnight", spirit: 9 },
  { username: "VenomFang", spirit: 9 },
  { username: "IronForge", spirit: 8 },
  { username: "SolarFlare", spirit: 8 },
  { username: "TerraByte", spirit: 8 },
  { username: "NovaBlaze", spirit: 7 },
];

export const sortedByIntelligenceDesc = [
  { username: "MysticEcho", intelligence: 20 },
  { username: "NebulaDrifter", intelligence: 20 },
  { username: "DarkOracle", intelligence: 20 },
  { username: "ChronoShift", intelligence: 20 },
  { username: "QuantumMage", intelligence: 19 },
  { username: "RuneMaster", intelligence: 19 },
  { username: "TerraByte", intelligence: 19 },
  { username: "CyberKnight", intelligence: 18 },
  { username: "ApexGamer", intelligence: 18 },
  { username: "SpiritDancer", intelligence: 18 },
  { username: "StarGazer", intelligence: 18 },
  { username: "AstralWalker", intelligence: 17 },
  { username: "ChaosTheory", intelligence: 17 },
  { username: "MysticEye", intelligence: 17 },
  { username: "ZenithSpark", intelligence: 16 },
  { username: "GravityPull", intelligence: 16 },
  { username: "IceQueen", intelligence: 16 },
  { username: "NovaBlaze", intelligence: 15 },
  { username: "SolarFlare", intelligence: 15 },
  { username: "EchoScream", intelligence: 15 },
  { username: "NeonPulse", intelligence: 15 },
  { username: "ApexHunter", intelligence: 15 },
  { username: "SilentViper", intelligence: 14 },
  { username: "PhantomBlade", intelligence: 14 },
  { username: "LunarTide", intelligence: 14 },
  { username: "OmegaPoint", intelligence: 14 },
  { username: "VoidRunner", intelligence: 13 },
  { username: "PixelKnight", intelligence: 13 },
  { username: "ShadowStep", intelligence: 13 },
  { username: "CrimsonTide", intelligence: 12 },
  { username: "AcidRain", intelligence: 12 },
  { username: "WildFire", intelligence: 12 },
  { username: "FireStorm", intelligence: 12 },
  { username: "RogueStellar", intelligence: 11 },
  { username: "VenomStrike", intelligence: 11 },
  { username: "StormBringer", intelligence: 11 },
  { username: "ApexPredator", intelligence: 10 },
  { username: "BlazeRunner", intelligence: 10 },
  { username: "SwiftArrow", intelligence: 10 },
  { username: "VenomFang", intelligence: 10 },
  { username: "FrostBite", intelligence: 9 },
  { username: "DragonSlayer", intelligence: 9 },
  { username: "ShadowHunter", intelligence: 8 },
  { username: "ThunderBolt", intelligence: 8 },
  { username: "IronWill", intelligence: 8 },
  { username: "SteelHeart", intelligence: 7 },
  { username: "TitanGrip", intelligence: 6 },
  { username: "TitanFall", intelligence: 6 },
  { username: "IronForge", intelligence: 5 },
];

export const hardcodedUser = {
  username: "BlazeRunner",
  intelligence: 1,
  strength: 1,
  stamina: 1,
  spirit: 11,
  endurance: 1,
  level: 1,
};

export const checkUser = {
  strength: false,
  stamina: false,
  endurance: false,
  spirit: true,
  intelligence: false,
};
